name: Automação Selenium - e-commerce Saucedemo
on: [push, pull_request]

jobs:
  Autimation-Saucedemo-Site_Compras:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Chrome and Driver
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile chrome_installer.exe
        Start-Process -FilePath .\chrome_installer.exe -Args "/silent /install" -Wait
        Remove-Item chrome_installer.exe
        python -m pip install webdriver-manager

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install numpy==1.24.3
        python -m pip install pytest pytest-html pytest-metadata

    - name: Install project dependencies
      run: |
        pip install --no-deps -r requirements.txt
        pip install moviepy==1.0.3 imageio==2.34.1 imageio-ffmpeg==0.6.0

    - name: Create pytest configuration
      shell: pwsh
      run: |
        $pytestConfig = @"
[pytest]
addopts =
    -v
    --html=relatorio_teste.html
    --self-contained-html
    --capture=sys
    --show-capture=log
metadata =
    Runner: GitHub Actions
    Python: 3.9
    Platform: Windows
"@
        $pytestConfig | Out-File -FilePath pytest.ini -Encoding utf8 -Force

    - name: Run Standard Test
      run: |
        pytest --html=relatorio_teste.html

    - name: Process and upload reports
      shell: pwsh
      run: |
        if (Test-Path relatorio_teste.html) {
            $content = Get-Content -Path relatorio_teste.html -Raw
            $content = $content -replace '<\s*br\s*/?>', '<br>' -replace '<\s*/\s*div\s*>', '</div>'
            $processedName = "processed_relatorio_teste.html"
            $content | Out-File -FilePath $processedName -Encoding utf8 -Force
            Write-Output "Processed relatorio_teste.html to $processedName"
        } else {
            Write-Warning "File relatorio_teste.html not found!"
        }

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: relatorios-automacao
        path: processed_relatorio_teste.html
        if-no-files-found: error
